apiVersion: v1
kind: ServiceAccount
metadata:
  name:  cart
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::334531533654:role/sss_eks_role_sa

---
apiVersion: v1
kind: Pod
metadata:
  name: cart
  labels:
    component: cart
spec:
  serviceAccountName: cart
  containers:
    - name: cart
      image: 334531533654.dkr.ecr.us-east-1.amazonaws.com/cart:2.0.0
      volumeMounts:
      - mountPath: /params
        name: params
  initContainers:
    - name: aws-ssm-param-store
      image : 334531533654.dkr.ecr.us-east-1.amazonaws.com/aws-ssm-param-store:3.0.0
      args: [ "sample:prod.docdb.pass"]
  volumes:
  - name: params
    emptyDir:
      sizeLimit: 100Mi
  
---
kind: Service
apiVersion: v1
metadata:
  name: cart
spec:
  selector:
    component: cart
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
