apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
    component: catalogue
spec: 
  containers:
    - name: catalogue
      image: 334531533654.dkr.ecr.us-east-1.amazonaws.com/catalogue:2.0.0

---

kind: Service
apiVersion: v1
metadata:
  name: catalogue
spec:
  selector:
    component: catalogue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      