apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    component: frontend
spec: 
  containers:
    - name: frontend
      image: 334531533654.dkr.ecr.us-east-1.amazonaws.com/frontend:2.0.0 
      

---

kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  selector:
    component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer