apiVersion: v1
kind: Pod
metadata:
  name: payment
  labels:
    component: payment
spec:
  containers:
    - name: payment
      image: 334531533654.dkr.ecr.us-east-1.amazonaws.com/payment:3.0.0

---
kind: Service
apiVersion: v1
metadata:
  name: payment
spec:
  selector:
    component: payment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
